# Generated by Django 4.2.6 on 2023-11-28 11:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0007_alter_fuel_used_entry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFoodChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=datetime.date(2023, 11, 28))),
                ('food_type', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('non_vegetarian', 'Non-Vegetarian'), ('ovo_vegetarian', 'Ovo-Vegetarian')], max_length=20)),
                ('total_food_emission', models.FloatField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_food_choices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
