# Generated by Django 4.2.6 on 2023-11-30 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_alter_dailyfoodchoice_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyfoodchoice',
            name='entry_date',
            field=models.DateField(default=datetime.date(2023, 11, 30)),
        ),
    ]
